[versions]
kotlin = "2.1.0"
jdk = "8"
compose = "2024.06.00"

[plugins]

[libraries]
plugin-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
